modLoader = "javafml"
loaderVersion = "${loader_version}"
issueTrackerURL = "https://github.com/leafreynolds/Cosmere/issues"
license = "MIT"

[[mods]]
modId = "hemalurgy"
version = "${version}"
displayName = "Cosmere: Hemalurgy"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/cosmere"
authors = "Leafy"
credits = '''

Arkamis - for the initial information in the guide book
Luke13234 - Who then updated it to what it is today

Special thanks go to:
Ridanisaurus - For many item and block textures.
'''
logoFile = "logo.png"
description = '''Hemalurgy module for Cosmere.'''

[[dependencies.hemalurgy]]
modId = "cosmere"
mandatory = true
versionRange = "[${version}]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hemalurgy]]
modId = "allomancy"
mandatory = false
versionRange = "[${version}]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hemalurgy]]
modId = "feruchemy"
mandatory = false
versionRange = "[${version}]"
ordering = "AFTER"
side = "BOTH"