modLoader = "javafml"
loaderVersion = "${loader_version}"
issueTrackerURL = "https://github.com/cosmere/Cosmere/issues"
license = "MIT"

[[mods]]
modId = "cosmere"
version = "${version}"
displayName = "Cosmere"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/cosmere/"
authors = "Leafy"
credits = '''

Ridanisaurus - For many item and block textures.
'''
logoFile = "logo.png"
description = '''Cosmere is a library mod, meant to be used with it's modules that add features from Brandon Sanderson's Cosmere universe.'''

[[dependencies.cosmere]]
modId = "minecraft"
mandatory = true
versionRange = "${mc_version}"
side = "BOTH"
[[dependencies.cosmere]]
modId = "forge"
mandatory = true
versionRange = "${forge_version}"
side = "BOTH"
[[dependencies.cosmere]]
modId = "curios"
mandatory = true
versionRange = "${curios_version}"
ordering = "AFTER"
side = "BOTH"
[[dependencies.cosmere]]
modId = "patchouli"
mandatory = false
versionRange = "${patchouli_version}"
ordering = "AFTER"
side = "BOTH"
[[dependencies.cosmere]]
modId = "jei"
mandatory = false
versionRange = "${jei_version}"
ordering = "AFTER"
side = "BOTH"
[[dependencies.cosmere]]
modId = "jade"
mandatory = false
versionRange = "${jade_version}"
ordering = "AFTER"
side = "BOTH"