modLoader = "javafml"
loaderVersion = "${loader_version}"
issueTrackerURL = "https://github.com/leafreynolds/Cosmere/issues"
license = "MIT"

[[mods]]
modId = "surgebinding"
version = "${version}"
displayName = "Cosmere: Surgebinding"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/cosmere"
authors = "Leafy"
credits = '''

Hawktrav - Various models and textures.
Luke13234 - Who wrote much of the Ars Arcanum guide book entries.
Eliot Lash - Implementation of Rosharan plant blocks and Cryptic model/animation.

Special thanks go to:
Ridanisaurus - For many item and block textures.
AlaharranHonor - For Rosharan plant blocks and textures.
'''
logoFile = "logo.png"
description = '''Surgebinding module for Cosmere.'''

[[dependencies.surgebinding]]
modId = "cosmere"
mandatory = true
versionRange = "[${version}]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.surgebinding]]
modId = "hemalurgy"
mandatory = false
versionRange = "[${version}]"
ordering = "BEFORE"
side = "BOTH"