name: Build Mod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon

      - name: Upload mod jar(s)
        uses: actions/upload-artifact@v4
        with:
          name: cosmere-1.20.1-mod-jars
          path: |
            build/libs/*.jar
          if-no-files-found: error
